### ISSUE TITLE
php-fpm doesn't start in PHP_FPM_CONTAINER_MODE=php-fpm

### ISSUE THREAD

**Issue by tchollingsworth** [tiredofit/docker-nginx-php-fpm#68]
### Summary

php-fpm doesn't start in `PHP_FPM_CONTAINER_MODE=php-fpm`

### Steps to reproduce

```
# minimal reproducer
docker run -d --name php-fpm-test -e PHP_FPM_CONTAINER_MODE=php-fpm tiredofit/nginx-php-fpm:8.3-alpine

# what I was actually trying to do
docker run -d --name fusiondirectory -e PHP_FPM_CONTAINER_MODE=php-fpm -e PHP_FPM_LISTEN_TYPE=tcp --env-file ldapopts tiredofit/fusiondirectory:1.4
```

### What is the expected *correct* behavior?

At least 1 `php-fpm` process is active in the contianer that is accessible over a Unix or TCP socket as configured.

### Relevant logs and/or screenshots

* [`docker logs php-fpm-test` with `DEBUG_MODE=true`](https://gist.github.com/tchollingsworth/2641d937bf8ffabc1157701de5cb0fa7#file-docker-log)
* [`docker top php-fpm-test`](https://gist.github.com/tchollingsworth/2641d937bf8ffabc1157701de5cb0fa7#file-docker-top)

### Environment

- Image version / tag:  `tiredofit/nginx-php-fpm:7.4-alpine` `tiredofit/nginx-php-fpm:8.3-alpine` `tiredofit/nginx-php-fpm:8.3-bookworm` `tiredofit/fusiondirectory:1.4` `tiredofit/fusiondirectory:1.4 rebuilt from git`
- Host OS: Debian GNU/Linux 12.2 bookworm `Linux 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux`

### Possible fixes

This doesn't seem good but `-e DONOTSTART=FALSE` didn't help either (of course lol)

```
+ echo 'DONOTSTART added by 20-php-fpm"'
+ DONOTSTART=TRUE
```

**Comment by tiredofit** [comment]
Let me look into - The Fusiondirectory container has TCP sockets by default as it hasn't been rebuilt in a while to support some of the changes in the 7.7.x base..

Hope to have something towards the end of the day.

**Comment by tiredofit** [comment]
Confirmed, what a weird behaviour occurring. Issue resolves way up in the base image chain and I am starting the rebuild process. Within 5 hours we should have a new image which should restore this to work the way you want it to..

However, any downstream images will need to be rebuilt as noted above - 
I also feel that the 8.3 alpine variant is not working as it should, investigating..

**Comment by tiredofit** [comment]
The original issue has been resolved in `7.7.3`. Since I saw you using FusionDirectory I also created a new release of the `1.4-` branch.

I also resolved the PHP 8.3 issues, so now alpine 8.3 images build properly!

Please confirm all is well on your end.

**Comment by tchollingsworth** [comment]
`nginx-php-fpm:7.4-alpine-7.7.3` and `fusiondirectory:1.4-2.8.4` are working very well, thank you so much!

Just so you know `nginx-php-fpm:8.3-alpine-7.7.3` [still fails](https://gist.github.com/tchollingsworth/678981af55ee6b9e6b35f0e5c35583ef) and goes into a loop trying to restart php-fpm but this doesn't bother me at the moment, I forgot 8.3 was released just a couple weeks ago I just wanted to test with something newer than 7.4 before I filed a bug.  🙂

**Comment by tiredofit** [comment]
Great! I'll look into the 8.3 issue tommorrow and solve it once and for all.
